[model]
type = "HeisenbergJ1J2"
J1 = 1.0

[scan]
parameter = "J2"
values = [0.0]

[circuit]
row = 4
p = 3
nqubits = 3
unit_cell = "two_by_two"
share_params = true

[optimization]
maxiter = 5000
abstol = 1e-5
sigma0 = 1.0
n_runs = 1
samples = 10000
conv_step = 100
measure_first = "Z"
seed = 123
